update=07/25/18 14:25:48
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=MoCo_v0.1-rescue
LibName2=power
LibName3=device
LibName4=switches
LibName5=relays
LibName6=motors
LibName7=transistors
LibName8=conn
LibName9=linear
LibName10=regul
LibName11=74xx
LibName12=cmos4000
LibName13=adc-dac
LibName14=memory
LibName15=xilinx
LibName16=microcontrollers
LibName17=dsp
LibName18=microchip
LibName19=analog_switches
LibName20=motorola
LibName21=texas
LibName22=intel
LibName23=audio
LibName24=interface
LibName25=digital-audio
LibName26=philips
LibName27=display
LibName28=cypress
LibName29=siliconi
LibName30=opto
LibName31=atmel
LibName32=contrib
LibName33=valves
LibName34=C:/Users/Aash Mohd/Downloads/pcb libraries/AUIRS2110S/KiCad/AUIRS2110S
LibName35=ice3br4765jgxuma1
LibName36=C:/Users/Aash Mohd/Downloads/QFP50P1400X1400X160-80N
LibName37=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Addressable-Specialty
LibName38=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Alarms-Buzzers-and-Sirens
LibName39=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Automotive-Relays
LibName40=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Balun
LibName41=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Barrel-Audio-Connectors
LibName42=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Battery-Holders-Clips-Contacts
LibName43=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Clock-Timing-Clock-Generators-PLLs-Frequency-Synthesizers
LibName44=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Clock-Timing-Programmable-Timers-and-Oscillators
LibName45=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Clock-Timing-Real-Time-Clocks
LibName46=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Coaxial-Connectors-RF
LibName47=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Current-Transducers
LibName48=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Data-Acquisition-ADCs-DACs-Special-Purpose
LibName49=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Data-Acquisition-Analog-to-Digital-Converters-ADC
LibName50=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Data-Acquisition-Digital-Potentiometers
LibName51=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Data-Acquisition-Digital-to-Analog-Converters-DAC
LibName52=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Data-Acquisition-Touch-Screen-Controllers
LibName53=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_DC-DC-Converters
LibName54=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Digital-Isolators
LibName55=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Diodes-Bridge-Rectifiers
LibName56=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Diodes-Rectifiers-Arrays
LibName57=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Diodes-Rectifiers-Single
LibName58=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Diodes-Zener-Single
LibName59=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Display-Modules-LCD-OLED-Graphic
LibName60=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Display-Modules-LED-Character-and-Numeric
LibName61=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_D-Sub-Connectors
LibName62=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Embedded-Microcontrollers
LibName63=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Encoders
LibName64=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Evaluation-Boards-Sensors
LibName65=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Ferrite-Beads-and-Chips
LibName66=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Fixed-Inductors
LibName67=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Fuses
LibName68=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Gas-Sensors
LibName69=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Humidity-Moisture-Sensors
LibName70=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Image-Sensors-Camera
LibName71=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Infrared-UV-Visible-Emitters
LibName72=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Inrush-Current-Limiters-ICL
LibName73=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Interface-Analog-Switches-Multiplexers-Demultiplexers
LibName74=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Interface-Analog-Switches-Special-Purpose
LibName75=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Interface-Controllers
LibName76=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Interface-Drivers-Receivers-Transceivers
LibName77=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Interface-I-O-Expanders
LibName78=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Interface-Modules
LibName79=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Interface-Sensor-and-Detector-Interfaces
LibName80=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Interface-Sensor-Capacitive-Touch
LibName81=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Interface-Specialized
LibName82=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_LED-Indication-Discrete
LibName83=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_LEDs-Circuit-Board-Indicators-Arrays-Light-Bars-Bar-Graphs
LibName84=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Linear-Amplifiers-Audio
LibName85=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Linear-Amplifiers-Instrumentation-OP-Amps-Buffer-Amps
LibName86=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Linear-Comparators
LibName87=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Logic-Buffers-Drivers-Receivers-Transceivers
LibName88=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Logic-Flip-Flops
LibName89=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Logic-Gates-and-Inverters
LibName90=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Logic-Multivibrators
LibName91=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Logic-Shift-Registers
LibName92=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Logic-Signal-Switches-Multiplexers-Decoders
LibName93=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Logic-Translators-Level-Shifters
LibName94=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Magnetic-Sensors-Compass-Magnetic-Field-Modules
LibName95=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Magnetic-Sensors-Linear-Compass-ICs
LibName96=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Magnetic-Sensors-Switches-Solid-State
LibName97=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Memory
LibName98=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Memory-Connectors-PC-Card-Sockets
LibName99=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Microphones
LibName100=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Modular-Connectors-Jacks
LibName101=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Modular-Connectors-Jacks-With-Magnetics
LibName102=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Motion-Sensors-Accelerometers
LibName103=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Motion-Sensors-IMUs-Inertial-Measurement-Units
LibName104=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Motion-Sensors-Tilt-Switches
LibName105=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Navigation-Switches-Joystick
LibName106=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Optical-Sensors-Ambient-Light-IR-UV-Sensors
LibName107=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Optical-Sensors-Photo-Detectors-Remote-Receiver
LibName108=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Optical-Sensors-Photodiodes
LibName109=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Optical-Sensors-Phototransistors
LibName110=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Optical-Sensors-Reflective-Analog-Output
LibName111=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Optoisolators-Logic-Output
LibName112=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Optoisolators-Transistor-Photovoltaic-Output
LibName113=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Optoisolators-Triac-SCR-Output
LibName114=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Oscillators
LibName115=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_PMIC-AC-DC-Converters-Offline-Switchers
LibName116=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Battery-Chargers
LibName117=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Battery-Management
LibName118=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Current-Regulation-Management
LibName119=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Full-Half-Bridge-Drivers
LibName120=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Gate-Drivers
LibName121=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_PMIC-LED-Drivers
LibName122=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Motor-Drivers-Controllers
LibName123=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_PMIC-OR-Controllers-Ideal-Diodes
LibName124=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Power-Distribution-Switches-Load-Drivers
LibName125=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Power-Management-Specialized
LibName126=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_PMIC-RMS-to-DC-Converters
LibName127=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Supervisors
LibName128=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Thermal-Management
LibName129=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_PMIC-V-F-and-F-V-Converters
LibName130=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Voltage-Reference
LibName131=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Voltage-Regulators-DC-DC-Switching-Controllers
LibName132=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Voltage-Regulators-DC-DC-Switching-Regulators
LibName133=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Voltage-Regulators-Linear
LibName134=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Voltage-Regulators-Special-Purpose
LibName135=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Power-Relays-Over-2-Amps
LibName136=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Pressure-Sensors-Transducers
LibName137=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Programmable-Oscillators
LibName138=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Pushbutton-Switches
LibName139=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Rectangular-Connectors-Headers-Male-Pins
LibName140=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Reed-Relays
LibName141=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Resistor-Networks-Arrays
LibName142=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_RF-Amplifiers
LibName143=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_RF-Antennas
LibName144=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_RF-Demodulators
LibName145=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_RF-Detectors
LibName146=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_RF-Evaluation-and-Development-Kits-Boards
LibName147=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_RFID-RF-Access-Monitoring-ICs
LibName148=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_RF-Receivers
LibName149=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_RF-Switches
LibName150=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_RF-Transceiver-ICs
LibName151=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_RF-Transceiver-Modules
LibName152=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_RF-Transmitters
LibName153=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Rotary-Potentiometers-Rheostats
LibName154=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Sensors-Transducers_Accessories
LibName155=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Signal-Relays-Up-to-2-Amps
LibName156=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Slide-Switches
LibName157=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Solid-State-Relays
LibName158=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Specialized-ICs
LibName159=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Specialized-Sensors
LibName160=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Surge-Suppression-ICs
LibName161=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Tactile-Switches
LibName162=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Temperature-Sensors-Analog-and-Digital-Output
LibName163=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Thermal-Cutoffs-Thermal-Fuses
LibName164=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Thyristors-DIACs-SIDACs
LibName165=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Thyristors-SCRs
LibName166=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Thyristors-TRIACs
LibName167=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Toggle-Switches
LibName168=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Transistors-Bipolar-BJT-Arrays
LibName169=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Transistors-Bipolar-BJT-RF
LibName170=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Transistors-Bipolar-BJT-Single
LibName171=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Transistors-Bipolar-BJT-Single-Pre-Biased
LibName172=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Transistors-FETs-MOSFETs-Arrays
LibName173=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Transistors-FETs-MOSFETs-RF
LibName174=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Transistors-FETs-MOSFETs-Single
LibName175=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Transistors-JFETs
LibName176=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_Trimmer-Potentiometers
LibName177=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_TVS-Diodes
LibName178=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_TVS-Mixed-Technology
LibName179=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/digikey-kicad-library-master/digikey-symbols/dk_USB-DVI-HDMI-Connectors
LibName180=C:/Users/Aash Mohd/Documents/vecmocon/zdacuments/KiCAD/KiCAD/symbols
LibName181=C:/Users/Aash Mohd/Documents/vecmocon/VECOMO/ffffffff/6ed project - V1.1/TJA1042
LibName182=LM324AMX_NOPB
LibName183=ina2181a1
[schematic_editor]
version=1
PageLayoutDescrFile=
PlotDirectoryName=
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=
SpiceForceRefPrefix=0
SpiceUseNetNumbers=0
LabSize=60
